apiVersion: apps/v1
kind: Deployment
metadata:
  name: webhook-server
  namespace: webhook-namespace  # Optional: Replace with your desired namespace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webhook-server
  template:
    metadata:
      labels:
        app: webhook-server
    spec:
      containers:
      - name: webhook-server
        image: <aws_account_id>.dkr.ecr.<region>.amazonaws.com/webhook-server:latest  # Replace with your ECR image
        ports:
        - containerPort: 5000
        env:
        - name: EMAIL_ADDRESS
          value: "karanagg1001@gmail.com"  # Replace with your email
        - name: EMAIL_PASSWORD
          value: "your-email-password"     # Replace with your email password
      nodeSelector:
        kubernetes.io/hostname: <specific-node-name>  # Replace with the name of your target node