apiVersion: apps/v1
kind: Deployment
metadata:
  name: webhook-server-jfrog
  namespace: webhook
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webhook-server-jfrog
  template:
    metadata:
      labels:
        app: webhook-server-jfrog
    spec:
      containers:
        - name: webhook-server
          image: 10.100.242.134:8081/pqrst/webhook-server:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
          env:
            - name: EMAIL_ADDRESS
              valueFrom:
                secretKeyRef:
                  name: email-credentials
                  key: EMAIL_ADDRESS
            - name: EMAIL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: email-credentials
                  key: EMAIL_PASSWORD
      imagePullSecrets:
        - name: artifactory-secret-new
