apiVersion: apps/v1
kind: Deployment
metadata:
  name: webhook-server
  namespace: webhook-namespace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webhook-server
  template:
    metadata:
      labels:
        app: webhook-server
    spec:
      containers:
      - name: webhook-server
        image: <aws_account_id>.dkr.ecr.<region>.amazonaws.com/webhook-server:latest  # Replace with actual image
        ports:
        - containerPort: 5000
        env:
        - name: EMAIL_ADDRESS
          valueFrom:
            secretKeyRef:
              name: email-credentials
              key: EMAIL_ADDRESS
        - name: EMAIL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: email-credentials
              key: EMAIL_PASSWORD
