apiVersion: apps/v1
kind: Deployment
metadata:
  name: webhook-server
  namespace: webhook
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webhook-server
  template:
    metadata:
      labels:
        app: webhook-server
    spec:
      containers:
      - name: webhook-server
        image: 961341544726.dkr.ecr.us-west-2.amazonaws.com/webhook/server:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
        env:
        - name: EMAIL_ADDRESS
          valueFrom:
            secretKeyRef:
              name: email-credentials
              key: EMAIL_ADDRESS
        - name: EMAIL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: email-credentials
              key: EMAIL_PASSWORD
      imagePullSecrets:
      - name: artifactory-secret
