apiVersion: v1
kind: Service
metadata:
  name: webhook-server-service
  namespace: webhook
spec:
  selector:
    app: webhook-server
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: LoadBalancer
